version: '3.9'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 5434:1433
    environment:
      MSSQL_SA_PASSWORD: "Pass@w0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - ./data:/var/opt/mssql/data
